### ISSUE TITLE
As an organizer, an edit button appears on the profiles of competition registrants

### ISSUE THREAD

**Issue by nsilvestri** [thewca/worldcubeassociation.org#7139] opened 2022-08-12 15:39 UTC
**Describe the bug**
I am an organizer for a yet-unannounced competition. I am not a delegate or other WCA staff member. On the profiles of the co-organizers and delegates associated with this competition (currently the only registered people), there is an edit button next to their name and I can view the edit page for their profile by clicking it. I can only see the General tab, and can't actually edit any of the properties there. However, the page does seem to think that I am the person who owns the edit page: it will tell me I cannot change "your name or gender", and says "Your WCA ID is XXXX", which is the other person's WCA ID.

**To Reproduce**
1. Be an organizer
2. Go to a registered person's profile
3. See and click the edit button next to their name

**Expected behavior**
As I am neither a delegate nor a member of the WCA who should have the ability to access the edit page, I should not be able to see the edit portion of other's profiles at all.

**Screenshots**
Not provided because personal information exists on the edit page.

**Additional context**
This may not be true for all registrants. It's also possible this bug only appears for delegates and co-organizers, but right now those are the same as the registrants so I cannot tell the difference.

**Comment by Jambrose777** [comment] 2022-08-12 16:05
Organizers currently need the ability to edit a persons information (specifically new competitors whose information may not be entered correctly). Most fields on the edit page are disabled for everyone when a WCA ID is connected.

In the future the WRT may investigate permissions and what different types of users should have access to, but that is currently not something that has been pursued as of now.

Closing as intended functionality and not a bug :)

**Closed by Jambrose777** 2022-08-12 16:05 UTC
