### ISSUE TITLE
Broken links in some WCA rankings pages

### ISSUE THREAD

**Issue by sebastianotronto** [thewca/worldcubeassociation.org#4860] opened 2019-11-18 14:22 UTC
**Bug description**
Links to cubers' profile pages in some WCA rankings (e.g. 4x4 average, 100 results) pages are broken. They redirect to non-existents pages such as https://cubecomps.worldcubeassociation.org, or directly to IP addresses such as https://34.208.140.116 (the latter seems to work, although it is considered unsafe by my browser). The issue is present when the language for the WCA website is set to English, but not for other languages (e.g. Italian).

**To Reproduce**
1. Set the worldcubeassociation.org language to English and go to 'https://www.worldcubeassociation.org/results/rankings/444/average?show=100+results'.
2. Click on any competitor's name (e.g. Max Park).
3. Link is broken.

Other pages present similar problems. For the "100 results, average" results, the following events are affected: 222 (links to 2fwww.worldcubeassociation), 444 (cubecomps.worldcubeassociation.org), Clock (ww.worldcubeassociation.org), Megaminx (34.208.140.116), Pyraminx (2fwww). Other events may be affected by selecting other types of results list (e.g. pyraminx 1000 results, average redirects to cubecomps.worldcubeassociation.org).

**Expected behavior**
These pages should link to the correct wca website.

**Screenshots**
![link](https://user-images.githubusercontent.com/14557809/69059668-3e5c0e00-0a16-11ea-9ca2-2a7db6dfeba1.png)
![link2](https://user-images.githubusercontent.com/14557809/69059676-41ef9500-0a16-11ea-81c9-66810a3beaa3.png)

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser: Firefox and Chromium

**Additional context**
The problem seems to appear only when using English as language for the WCA website (and possibly other languages, I haven't tested them all).

**Comment by EdHollingdale** [comment] 2019-11-18 14:25
Looks similar to #4604 as well. It'd be great to get to the bottom of this!

**Comment by moralsh** [comment] 2019-11-25 20:48
problem seems to be with ENVied.ROOT_URL which seems to be mixing up the ROOT_URL with another environment variable defined with the same name in the server, as to why it only happens with English I don't have any idea, beats me. 

Maybe changing the name of the environment to something less generic could be a workaround,

**Comment by viroulep** [comment] 2019-11-29 17:44
We just merged #4486, I'm gonna assume it fixed that because I can't reproduce.
Please do feel free to re-open if you notice the issue again!

**Closed by viroulep** 2019-11-29 17:44 UTC
