### ISSUE TITLE
Note for competitors when competition is full

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#1567] opened 2017-04-26 23:07 UTC
In my experience so far with Rose City 2017, we have already had a few competitors email us regarding why their registration has not been accepted. Many of them did not check how many competitors had registered and thought that there were open spots by registration being open. 

Ideally, it would be nice to have a field for a competitor limit, and an associated message to show on the registration page when the number of registered competitors reaches this limit. The message could be something along the lines of:

> The competitor limit for this competition has been reached already. You can still use this form to sign up for the waiting list for this competition, so that if a competitor cannot attend the competition, you still may be eligible to compete. To be considered for being removed from the waiting list, you may need to pay the registration fee, see the competition website for more details.
> There are currently X competitors on the waiting list and Y competitors on the waiting list who have completed payment.

**Comment by jfly** [comment] 2017-04-27 15:25
Yes, this is definitely something we're sorely lacking. Closing as a duplicate of #328.

**Closed by jfly** 2017-04-27 15:25 UTC
Labels: registration
