### ISSUE TITLE
Remove illegal cutoff formats

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#8494] opened 2023-11-07 00:22 UTC
This has been already started [here](https://github.com/thewca/worldcubeassociation.org/pull/6593), but couldn't complete it. If somebody is interested to continue from there, please feel free to take it up after dropping a comment here.

**Comment by dunkOnIT** [comment] 2024-03-03 06:42
Closed as duplicate of #7555

**Closed by dunkOnIT** 2024-03-03 06:42 UTC
Labels: TECH: ruby
