### ISSUE TITLE
Redesign the navigation bar

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#5457] opened 2020-05-18 20:17 UTC
The current navigation bar is a bit ugly with regard to the intended new homepage design (see #5340), and could benefit from a makeover.
Laura actually did suggest a design on which we could base our work.

As very limited user interaction is expected (ie: only links to click and basic dropdown), this is a pure html issue (with the exception of the - already existing - rails-generated links to pages).

This is kind of related to #5456, as we need the omnisearch component in the navigation.

**Comment by shzcuber** [comment] 2020-11-21 18:03
Hello,

I'm interested in giving this issue a shot as my first issue in this repository, but I have some questions. Is there some sort of concrete guideline to follow for the redesign? Is this (the following screenshot) the navbar to redesign?
![image](https://user-images.githubusercontent.com/60201722/99884128-88a33c80-2be0-11eb-9e40-7549db5868af.png)

Thanks!

**Comment by jonatanklosko** [comment] 2020-11-22 16:23
Hey Shawn, [here](https://projects.invisionapp.com/share/UKPIXG16QBM#/screens/335893357)'s a mockup created by Laura Ohrndorf, but the navbar doesn't include all the elements (especially dropdown lists), so feel free to treat it as an inspiration, but the final looks is definitely not concretely specified. If you want to give it a shoot the relevant files are [_navigation.html.erb](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/layouts/_navigation.html.erb) and [navbar-static-top.scss](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/assets/stylesheets/navbar-static-top.scss).

**Comment by shzcuber** [comment] 2020-11-24 19:46
#5904 

Created a pull request. I'm a newbie at HTML and CSS, so please let me know if I need to change or add anything, and I'll be happy to fix it. Thanks!

**Comment by moralsh** [comment] 2020-11-24 19:58
Could you post a screenshot to let more people comment on it without having to apply your changes?

**Comment by shzcuber** [comment] 2020-11-24 20:02
Sure! 
Front page (desktop)
![image](https://user-images.githubusercontent.com/60201722/100145111-ad035100-2e4c-11eb-8f35-a84d319fe63b.png)
Mobile version: 
![image](https://user-images.githubusercontent.com/60201722/100145292-f5bb0a00-2e4c-11eb-895f-8104c7bfa2b8.png)
![image](https://user-images.githubusercontent.com/60201722/100145305-f9e72780-2e4c-11eb-80a6-c6aff46dceae.png)

**Comment by jonatanklosko** [comment] 2020-11-25 01:26
I like this direction! I would be happy to hear what vision others have. As for my suggestions:

1. I strongly believe it actually looks better without the grey color (look up the `#ccc` and `#ddd` colors in the scss file).
2. I think the social media icons outside of navbar look weird. We could place them above te navbar (as in the mockup), but that takes a bit of space. One alternative I can think of is just adding a new expandable navigation option with all the links.

**Comment by viroulep** [comment] 2020-11-25 08:07
Thanks @shzcuber for starting working on this!

It's not explicit in the issue description, but one of the goal of the issue was to migrate the navigation bar from using bootstrap's component to fomantic ui's (which can actually be a bit tricky).
I can definitely see how the "look changes" and "framework changes" can be handled separately, so if just one of them is done we should just remember to either not close this or to create another specific issue for the remaining part.

**Comment by shzcuber** [comment] 2020-11-25 15:22
Thanks Jonatan and Phillippe for the feedback! I will be implementing a new dropdown for the social media links, and changing the background color. As for the Formantic UI migration, I'll try to learn the framework (just like I did with bootstrap) and give it  shot!

**Comment by viroulep** [comment] 2020-11-25 15:34
Sounds great!
I'd expect you'll face two challenges (apart from actually learning the FUI components):
  - we have both bootstrap and fui's css included in the website, which may lead to different looking layouts from FUI's documentation. We do load FUI last, so if there are css classes conflicts, FUI will override (hopefully it's just a matter of avoiding bootstrap-specific classes).
  - the omnisearch engine is not ported to FUI yet (and it's honestly not the most beginner-friendly task, even if I started a PoC [here](https://github.com/viroulep/worldcubeassociation.org/pull/1/commits/9b30f5088fe845bca00649cf41840016fcb35464) when redesigning the homepage). But it may be possible to restyle the search field while keeping the current javascript behavior (if it is not, it should be fine to let it as-is, hoping that the visual contrast wouldn't be too annoying).

**Comment by shzcuber** [comment] 2020-11-25 16:03
Thanks, will keep those in mind.

**Comment by campos20** [comment] 2020-11-25 21:11
> Sounds great!
> I'd expect you'll face two challenges (apart from actually learning the FUI components):
> 
> * we have both bootstrap and fui's css included in the website, which may lead to different looking layouts from FUI's documentation. We do load FUI last, so if there are css classes conflicts, FUI will override (hopefully it's just a matter of avoiding bootstrap-specific classes).
> * the omnisearch engine is not ported to FUI yet (and it's honestly not the most beginner-friendly task, even if I started a PoC [here](https://github.com/viroulep/worldcubeassociation.org/pull/1/commits/9b30f5088fe845bca00649cf41840016fcb35464) when redesigning the homepage). But it may be possible to restyle the search field while keeping the current javascript behavior (if it is not, it should be fine to let it as-is, hoping that the visual contrast wouldn't be too annoying).

Is the bootstrap's css fully loaded? Because I remember trying to use some classe that showed no effect. I'm not sure if it were some overridden thing.

Also, good to note that the docker implementation is showing results. As far as I can tell, Shawn codes in Windows.

**Comment by shzcuber** [comment] 2020-11-26 02:30
Hello, 

Sorry for the bother, but I'm having trouble with FUI. To practice and learn the framework, I tried to run sample code from the website. It works perfectly here in fiddle: https://jsfiddle.net/0fwm32ge/1/  However, on the website, the dropdowns are not hidden. Does anyone know the problem? I will include the code and images of my problem below.
```html
<div class="ui menu">
  <a class="item">
    Home
  </a>
  <div class="ui pointing dropdown link item">
    <span class="text">Shopping</span>
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="header">Categories</div>
      <div class="item">
        <i class="dropdown icon"></i>
        <span class="text">Clothing</span>
        <div class="menu">
          <div class="header">Mens</div>
          <div class="item">Shirts</div>
          <div class="item">Pants</div>
          <div class="item">Jeans</div>
          <div class="item">Shoes</div>
          <div class="divider"></div>
          <div class="header">Womens</div>
          <div class="item">Dresses</div>
          <div class="item">Shoes</div>
          <div class="item">Bags</div>
        </div>
      </div>
      <div class="item">Home Goods</div>
      <div class="item">Bedroom</div>
      <div class="divider"></div>
      <div class="header">Order</div>
      <div class="item">Status</div>
      <div class="item">Cancellations</div>
    </div>
  </div>
  <a class="item">
    Forums
  </a>
  <a class="item">
    Contact Us
  </a>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
$('.ui.dropdown')
  .dropdown({
    on: 'hover'
  })
;
</script>
```
![image](https://user-images.githubusercontent.com/60201722/100300992-0a31fc00-2f4c-11eb-9b9f-c9a7332947c5.png)

Here is the code if anyone wants to reproduce the issue: https://github.com/shzcuber/worldcubeassociation.org/tree/switch-to-fomantic

Thanks in advance.

**Comment by viroulep** [comment] 2020-11-26 20:54
Ah, I think the javascript part is missing and it's because we don't load all "plain javascript" files from fomantic ui: the goal is to have all the new javascript-related development in react (jquery-free, as much as possible), using the "webpack" part of rails (a lot of our current javascript still contains a lot of jquery and is managed through sprockets).
There is a wiki article describing the rationale and guide for writing/integrating React components in the website [here](https://github.com/thewca/worldcubeassociation.org/wiki/Writing-a-new-React-component).

I totally overlooked we would need js for the navigation; ideally we would port the navigation to react, but that definitely relies heavily on #5456.
I don't have a great suggestion for solving everything right now.
I think that regardless of the framework we can redesign the navigation bar, and however it looks it should be possible to closely match its look in a different framework (which basically means you could focus on giving the navigation a new look in the current framework, without having to worry about unveiling a whole lot of issues coming from the port to react).

On a related note: I've seen that you added `fomantic-sass` in your changes: this is actually not necessary, as we load FUI's css in [this pack](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/webpacker/packs/global_styles.js), which is included in all the website page.
You just need to add `import 'semantic-css/dropdown';` in the pack I mentionned.

Actually: reading the pack and taking another look at our FUI's files made me realize that you *could* achieve what you want.
Additionally to the css, you could also import the dropdown-related js by adding `import '../stylesheets/semantic/components/dropdown.min';` to the `global_styles` pack!
This kind of breaks the "new component" => "react" rule, but:
  - we're far from dropping jquery
  - the necessary component for the search bar doesn't exist
  - it would be extremely straightforward to port the navigation to react when it does exist

The changes are simple enough to give it a go I think!
(I haven't actually tested them, so if it doesn't work let me know :))

**Comment by shzcuber** [comment] 2020-11-27 23:13
Thanks for the reply! Really gives me insight on the structure of the project, as a new contributor. However, I have a couple questions. 

1) As you told me to "focus on giving the navigation a new look in the current framework, without having to worry about unveiling a whole lot of issues coming from the port to react", does this mean I should continue using bootstrap to redesign the navigation bar? 
2) I imported both `semantic-css/dropdown` and `'../stylesheets/semantic/components/dropdown.min';` to `global_styles`, and it did hide the dropdowns, but did not reveal the dropdowns on click. Would I need to write jQuery for that? If so, where should I insert the jQuery?

Thanks for your time, and please let me know if I'm not understanding something well.

**Comment by viroulep** [comment] 2020-11-28 08:24
The bootstrap+fui pain is real :(
I tried a basic dropdown example from FUI locally to investigate the behavior you observed (I did run into it), and running `console.log($('.ui.dropdown').dropdown);` in the js console shown that the function belonged to bootstrap.
Since both framework extend jquery, my guess is that either:
  - bootstrap overrides `dropdown` no matter what
  - fui detects that a `dropdown` function is already present and does nothing

I could make it work [here](https://github.com/viroulep/worldcubeassociation.org/commit/f530be12947f4b28933208fd8852606904253d7f) by preventing bootstrap's js from loading, but this obviously breaks the website in a lot of places, and not something we can reasonably do just yet.
I also wanted to check only dropdown from FUI was required, but it turns out you also need transitions.

About 1: sorry for the confusion, when writing my answer I initially thought it was not possible, then realize it might be possible, and decided to not remove my initial though process.
But given I don't see a not dirty way to resolve the conflict between FUI and bootstrap, yes, I think you should continue using bootstrap to redesign the navigation bar :)
(that being said, if once you have the resulting navbar you want to practice FUI and reproduce the same navbar using FUI in a jsfiddle, please feel free to do so: I sure it will come in handy when #5456 is done :D)

**Comment by shzcuber** [comment] 2020-11-28 17:41
Got it, thanks for clearing everything up! Here is the current navigation bar redesigned with Jonatan's suggestions: 
![image](https://user-images.githubusercontent.com/60201722/100522110-5acc7380-315d-11eb-81cc-a36ce7c6de59.png)

Anything I should fix/add?

**Comment by shzcuber** [comment] 2020-11-29 15:48
It seems like my pull request #5904 failed all the checks. How would I correct that?

**Comment by jonatanklosko** [comment] 2020-11-29 16:15
> It seems like my pull request #5904 failed all the checks. How would I correct that?

Commented on that on the PR.

Before looking into the code, does it look ok on mobile having the title ale icons removed?

**Comment by shzcuber** [comment] 2020-11-29 16:20
![image](https://user-images.githubusercontent.com/60201722/100547442-a6455700-321b-11eb-82c7-65d6ae849acb.png)


It seems to look alright - always open to suggestions, of course :)

**Comment by jonatanklosko** [comment] 2020-11-29 16:26
Look alright to me! The search bar could be a little bit smaller (ideally 100% width with some padding), as it looks like it causes the horizontal scroll. Also the hamburger icon is not centered vertically, so it could also be slightly adjusted.

**Comment by shzcuber** [comment] 2020-11-29 16:33
![image](https://user-images.githubusercontent.com/60201722/100547802-929af000-321d-11eb-8efa-acc59af9f24a.png)

Does this work?

**Comment by jonatanklosko** [comment] 2020-11-29 16:35
Now the logo kinda gets out of the navbar, I'd rather keep it inside ^^

**Comment by shzcuber** [comment] 2020-11-29 16:36
![image](https://user-images.githubusercontent.com/60201722/100547877-00471c00-321e-11eb-86e5-35fe0f7f63c6.png)

Right, somehow missed that haha. Hopefully this works now

**Comment by jonatanklosko** [comment] 2020-11-29 16:42
Great, I like that! Would be happy to see what others think, I'll send a quick email to the Communication Team to check with them.

**Comment by c-goodyear** [comment] 2020-11-29 18:15
> Look alright to me! The search bar could be a little bit smaller (ideally 100% width with some padding), as it looks like it causes the horizontal scroll. Also the hamburger icon is not centered vertically, so it could also be slightly adjusted.

I think this is also causing this issue at different zooms if settings are trying to avoid displaying horizontal scrolling
90% zoom - search is inline
<img width="1078" alt="90perc" src="https://user-images.githubusercontent.com/45567122/100550007-16cd9180-3277-11eb-8e0c-b0b79dd55dc8.PNG">

100% zoom - search gets "bumped" lower
<img width="1080" alt="100perc" src="https://user-images.githubusercontent.com/45567122/100550008-17662800-3277-11eb-94cb-ef545c472deb.PNG">

110% zoom - back to normal :-D
<img width="1080" alt="110perc" src="https://user-images.githubusercontent.com/45567122/100550009-17febe80-3277-11eb-97a9-329d091dc94c.PNG">

**Comment by shzcuber** [comment] 2020-11-29 18:18
Thanks for catching that -  I ended up resizing the search bar to fix that issue. 
![image](https://user-images.githubusercontent.com/60201722/100550067-28d61280-322c-11eb-9e41-2d5f8d9d56e2.png)

I don't know if this is too small though - is there a better way to fix this?

**Comment by c-goodyear** [comment] 2020-11-29 18:29
What about if the search bar is small when the cursor is not placed in it. Then when the cursor is inside it, the dropdowns to the left could collapse to only show their icons, thus making the search bar wider in their place.

Something like this? (But the search bar would become longer, I just forced this icon collapse with zoom)
![image](https://user-images.githubusercontent.com/45567122/100550269-0f0eec80-3279-11eb-9ed2-ea631e8ac3e1.png)

**Comment by shzcuber** [comment] 2020-11-29 19:46
That's a good solution - not too sure how I would go about that though (I didn't create the icon collapse). I'll give it a shot and see what I can do.

**Comment by lgarron** [comment] 2020-11-29 20:22
*woo* this is fabulous. Getting a unified navbar at all back in the day was a feat, but I'm glad to see it go.

I have a fairly large accessbility concern, which is that the dropdowns do not have a focus ring:

<img width="231" alt="Screen Shot 2020-11-29 at 12 20 49" src="https://user-images.githubusercontent.com/248078/100552657-5bd4d200-323d-11eb-9587-2d75d1d522dc.png">

Compare that to the logo and the non-dropdown menu item:
<img width="125" alt="Screen Shot 2020-11-29 at 12 20 51" src="https://user-images.githubusercontent.com/248078/100552653-59727800-323d-11eb-8f25-91f2eda63302.png">
<img width="145" alt="Screen Shot 2020-11-29 at 12 20 47" src="https://user-images.githubusercontent.com/248078/100552651-58d9e180-323d-11eb-90c2-9f26faaeed12.png">

(The hover background is also inconsistent between dropdown and non-dropdown and is fairly subtle.)

Also, as a minor nit, it feels odd to me that the navbar has 4px padding at the bottom, but not on the other sides. This means the logo is not centered, and dropdown highlights are also not centered. Would it be possible to add 4px padding on top as well?

![Uploading Screen Shot 2020-11-29 at 12.19.12.png…]()

**Comment by lgarron** [comment] 2020-11-29 20:27
Also, the logo gets a little bit less legible at this resolution. You might be interested in updating it with a cleaned-up SVG  I made where the lines are more visible at smaller resolution:

<img width="470" alt="Screen Shot 2020-11-29 at 12 26 55" src="https://user-images.githubusercontent.com/248078/100552791-32687600-323e-11eb-989b-23d70afdfe94.png">


https://www.dropbox.com/s/01qhwutfyb9a0oq/WCA%20Logo%202020.svg?dl=0

**Comment by shzcuber** [comment] 2020-11-29 20:58
Thanks so much for the feedback!

I added the logo, and here's what the navbar looks like now when you hover over either the logo or the forum element: 
![image](https://user-images.githubusercontent.com/60201722/100553337-66459a80-3242-11eb-8e02-0d8c2f5cea0d.png)
![image](https://user-images.githubusercontent.com/60201722/100553341-6cd41200-3242-11eb-81a5-64201ddd1cb9.png)

As for the padding, Jonatan gave me a good fix for that, but I don't think it's deployed on the staging website yet. Hopefully it's clear in the screenshots.

**Comment by lgarron** [comment] 2020-11-30 03:13
> Hopefully it's clear in the screenshots.

It is!

I'm actually a fan of the padding, especially to avoid bumping the icon into the edge. Just wanted to ask for it to be symmetric. :-P
(As an alternative, the icon can be put into a `border-box` padded wrapper.)

**Comment by shzcuber** [comment] 2020-11-30 03:39
Oh, I see what you mean. Here's a 5px vertical padding:
![image](https://user-images.githubusercontent.com/60201722/100566294-85f8b500-327a-11eb-83c6-ba76c16b3140.png)

You like?

**Comment by EvilAngel00** [comment] 2020-11-30 10:11
Hi @shzcuber, thanks for working on that, it looks very promising!

I have a couple of remarks:

* The "Information" button is darker by default (without hovering), is this intended? I actually just noticed that it's also the case on the normal website so this might be a question for a broader audience :)
* I feel like the logo should be either bigger or not touching to the borders but making the logo even smaller doesn't make too much sense. I don't have a good suggestion at the moment, unless we rethink the logo placement and replace it with a "Home" button on the navbar instead. The WCT is also working on trying to unify the logo design across different pages (i.e. [website](https://www.worldcubeassociation.org/assets/wca_logo-bc89f32537437455803c7c9bcc2691bbddbcdf8558282aaea1d9386d7a3cd802.svg), [forum](https://forum.worldcubeassociation.org/uploads/default/original/1X/b2f451a263fa26013c633619f0d3f42addbb3e23.png) and [WCA Live](https://live.worldcubeassociation.org/static/media/logo.201c360e.svg) so it could be a good time to think about that.

**Comment by shzcuber** [comment] 2020-11-30 15:18
Thanks for the suggestions!
> The "Information" button is darker by default (without hovering), is this intended? I actually just noticed that it's also the case on the normal website so this might be a question for a broader audience :)

Yeah, I was wondering about that too. I removed the default dark shade for now - please let me know if you want me to re-add it again.
> I feel like the logo should be either bigger or not touching to the borders but making the logo even smaller doesn't make too much sense. I don't have a good suggestion at the moment, unless we rethink the logo placement and replace it with a "Home" button on the navbar instead. The WCT is also working on trying to unify the logo design across different pages (i.e. website, forum and WCA Live so it could be a good time to think about that.

I see. I actually added 5px vertical padding to the navbar through Lucas Garron's suggestions, so the logo is no longer touching the borders (see image below). 
![image](https://user-images.githubusercontent.com/60201722/100627666-1ddabb00-32dc-11eb-80f0-b8872a234f52.png)

**Comment by shzcuber** [comment] 2020-12-05 18:51
Hello,

Just wondering if there's anything else I need to do with the nav bar :)

**Comment by jonatanklosko** [comment] 2020-12-07 00:25
Fixed by #5904.

**Closed by jonatanklosko** 2020-12-07 00:25 UTC
Labels: design, good first issue

**Comment by lgarron** [comment] 2020-12-11 22:46
Glad to see this in action!

It seems that left padding for the icon is missing for the narrow version; is that worth a separate bug?
<img width="98" alt="Screen Shot 2020-12-11 at 14 45 36" src="https://user-images.githubusercontent.com/248078/101961868-89b40200-3bbf-11eb-82de-785f1101d98a.png">

**Comment by shzcuber** [comment] 2020-12-12 06:11
![image](https://user-images.githubusercontent.com/60201722/101976799-bedf4500-3bfd-11eb-8f2c-a67b4d2c2ceb.png)

Added the same amount of padding as the normal sized version, hopefully this works. #5932
