### ISSUE TITLE
Warnings for WCAT

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#4470] opened 2019-08-14 01:20 UTC
This issue is to collect suggestions from WCAT on warnings that would be helpful for announcing competitions, beyond #3225 

Clément suggests having a warning when we have a round listed more than once in the schedule.

**Comment by viroulep** [comment] 2019-08-14 07:15
This particular warning is a duplicate of #3335.
If there are warnings that are not related to events/schedule we should be fine keeping that open, but if not I think we can close this and use the existing issue :)

**Comment by AlbertoPdRF** [comment] 2019-08-14 09:14
@Jambrose777 already added quite a few on #4144, and if there are more needed they are probably already listed on the issues of [the competition form project](https://github.com/thewca/worldcubeassociation.org/projects/8), so I'm closing this one.

**Closed by AlbertoPdRF** 2019-08-14 09:14 UTC
