### ISSUE TITLE
Don't allow competitors to delete their own registrations

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#6809] opened 2022-04-06 05:13 UTC
When allowing competitors to edit their registrations, I appreciate allowing people to edit their registrations without emailing me. But when competitors delete their registrations, their intent is unclear. For some, this is an accident, and it's impossible to tell when it is intentional or not from the organizer's perspective. 

It would be nice if the default behavior was to force any deletion to be done via email, even if the setting is to allow registration edits. For competitions that are full with a waiting list, allowing competitors to delete makes it appear that there is a spot open for some time, giving those who register shortly after the deleting the false impression that they will be accepted into the competition.

**Comment by EdHollingdale** [comment] 2022-04-15 04:03
I think this issue is a duplicate of #6621, but it shows how great it would be if that could be resolved...

**Comment by gregorbg** [comment] 2022-09-01 03:06
Fixed per #6991 as mentioned in #6621

**Closed by gregorbg** 2022-09-01 03:06 UTC
Labels: CONVERT-TO-PROJECT: registration
