### ISSUE TITLE
the missing averages isnt needed anymore

### ISSUE THREAD

**Issue by judepirnat** [thewca/worldcubeassociation.org#5728] opened 2020-09-24 13:27 UTC
mo3 for 5bld and 4bld is now on the leaderboards and the missing averages page shows the mo3 for those events

**Comment by Jambrose777** [comment] 2020-10-07 00:05
Duplicate of https://github.com/thewca/worldcubeassociation.org/issues/4106

**Closed** 2020-12-27 16:15 UTC
