### ISSUE TITLE
Issues with non-latin characters in search results

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1547] opened 2017-04-20 09:37 UTC
See the following screenshot:
![characters-in-search-results](https://cloud.githubusercontent.com/assets/1007485/25224061/8e13cf68-25bd-11e7-9f8a-b9109f09d5ab.png)

Also "Jonatan Kłosko" is actually displayed "Jonatan Klosko" so we probably do some name manipulation that we shouldn't before displaying the search results!

**Comment by jfly** [comment] 2017-04-20 17:07
Closing as this is a duplicate of https://github.com/thewca/worldcubeassociation.org/issues/238 =)

If your'e motivated to resurrect https://github.com/jfly/translighterate, we could get this fixed. That gem is currently not a drop in replacement for us because of https://github.com/jfly/translighterate/issues/2.

**Closed by jfly** 2017-04-20 17:07 UTC
Labels: bug
