### ISSUE TITLE
undefined method `empty?' for nil:NilClass when editing a competition with validation errors

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1016] opened 2016-11-17 01:01 UTC
See:

![image](https://cloud.githubusercontent.com/assets/277474/20372111/e8c379d2-ac1d-11e6-958e-c8506e2e8066.png)

@pedrosino, I believe this is due to the fact that [the validation error codepath](https://github.com/thewca/worldcubeassociation.org/blob/a8b10d4dbda23da6b70dac93a4bd9fa9830089da/WcaOnRails/app/controllers/competitions_controller.rb#L343-L351) causes us to render `edit` without first setting `@nearby_competitions`.

**Comment by viroulep** [comment] 2016-11-23 17:03
@pedrosino's fix is merged and there on production, yet when I tried to create a dummy competition for new year's eve I forgot to set some name and ran into this (from production log):

```
I, [2016-11-23T16:47:34.901007 #29128]  INFO -- : Completed 500 Internal Server Error in 115ms (ActiveRecord: 18.3ms)
I, [2016-11-23T16:47:34.901214 #29128]  INFO -- : [User Id] Request was made by user id: 277
F, [2016-11-23T16:47:34.903333 #29128] FATAL -- : 
ActionView::Template::Error (undefined method `empty?' for nil:NilClass):
    10:   </label>
    11:   <div class="col-sm-9">
    12:     <% if @competition.has_date? && @competition.has_location? %>
    13:       <% if @nearby_competitions.empty? %>
    14:         <%= alert :success, t('.no_comp_nearby') %>
    15:       <% else %>
    16:         <%= render 'nearby_competitions_table', nearby_competitions: @nearby_competitions %>
  app/views/competitions/_nearby_competitions.html.erb:13:in `_app_views_competitions__nearby_competitions_html_erb__3278230220330066205_40311000'
  app/views/competitions/_competition_form.html.erb:207:in `block in _app_views_competitions__competition_form_html_erb__1171541471265455478_33403420'
  app/helpers/application_helper.rb:152:in `block in simple_form_for'
  app/helpers/application_helper.rb:150:in `simple_form_for'
  app/helpers/application_helper.rb:168:in `horizontal_simple_form_for'
  app/views/competitions/_competition_form.html.erb:3:in `_app_views_competitions__competition_form_html_erb__1171541471265455478_33403420'
  app/views/competitions/new.html.erb:8:in `_app_views_competitions_new_html_erb___572707152669768588_33886360'
  app/controllers/competitions_controller.rb:133:in `create'
  lib/middlewares/warden_user_logger.rb:12:in `call'
  lib/middlewares/fix_accept_header.rb:13:in `call'
```

It's easy to reproduce as to just have to clone an existing competition, set any valid date and click create :)
It seems that even with a date and a location the `@nearby_competitions` is `nil` when the competition has validation errors :s

**Comment by pedrosino** [comment] 2016-11-23 18:15
Just as before (with update action), this seems to be at the create action. Before rendering new (in case of fail), we must set the @nearby_competitions object at https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/competitions_controller.rb#L133

**Closed** 2016-11-24 12:45 UTC
Labels: bug
