### ISSUE TITLE
Showing wrong past competitions

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/worldcubeassociation.org#1947] opened 2017-09-20 19:25 UTC
So this is something that has been bothering me for some time, when going under "my competitions" it says that I have been to more competitions than I have, because when you have registered and then unregistered, it saves it, and has the sign waiting for results.
![image](https://user-images.githubusercontent.com/28397408/30663194-2167416e-9e4a-11e7-9062-4493314e4d2d.png)
![image](https://user-images.githubusercontent.com/28397408/30663040-8f59c382-9e49-11e7-8517-73b623194859.png)
![image](https://user-images.githubusercontent.com/28397408/30663050-9b89244a-9e49-11e7-8641-807eb9ba49fc.png)
So my proposal would be for it to automatically remove it, when you are no longer listed under the competitior list.

Daniel (2013EGDA01)

**Comment by viroulep** [comment] 2017-09-21 08:08
I'd argue it's not a bug since it's a known behavior and we were fine with it :stuck_out_tongue: 

However it's been bothering for quite some people as we regularly receive comments about this.
The fix is probably as easy as scoping the competitions a user is registered for as `not_over`.
(ie: changing [this line](https://github.com/thewca/worldcubeassociation.org/blob/27b6d6b9bafab5d5b8dd0be3c9de56a3c344b06b/WcaOnRails/app/controllers/competitions_controller.rb#L509)), or better filter them with `results_posted?`, as if the results are posted they will be selected through the `Person` model a line below.

This will mean people without a claimed WCA ID won't see their previous registrations once results are posted, will wonder what's going on, and hopefully finally claim their ID (I think this is a good change).

I may be mislead by your comment [here](https://github.com/thewca/worldcubeassociation.org/issues/1746#issuecomment-330607175), but it sounds like you may be interested in contributing here, and this kind of fix would be good for people not familiar with the codebase.

So I'm intentionally not fixing it yet ;)

**Comment by Mollerz** [comment] 2017-09-21 10:49
It might be an idea so that if you go to the past competitions page and it shows 0 competitions, it could ask a little question saying "Have you competed before? You will need to claim your WCAID! <Link here>".

It would also need to check if you are a delegate for the competition, since some delegates do not compete. For example Ivo Kruusamägi does not compete, but has delegated all Estonian competitions.

**Comment by DanielEgdal** [comment] 2017-09-21 11:05
I like James' suggestion :)

**Comment by viroulep** [comment] 2017-09-21 12:12
Currently the code already looks at delegated/organized competition:
https://github.com/thewca/worldcubeassociation.org/blob/27b6d6b9bafab5d5b8dd0be3c9de56a3c344b06b/WcaOnRails/app/controllers/competitions_controller.rb#L509
And then add up competition for which your person has results:
https://github.com/thewca/worldcubeassociation.org/blob/27b6d6b9bafab5d5b8dd0be3c9de56a3c344b06b/WcaOnRails/app/controllers/competitions_controller.rb#L511

The alert when a competitor has 0 competitions at the end of it is a good idea!

**Comment by jfly** [comment] 2017-09-22 18:00
The reason we have not made this change is because we don't want competitions to disappear from people's "my competitions" list when a competition is over, but the results are not yet uploaded.

I'm going to close this in favor of #1407.

**Closed by jfly** 2017-09-22 18:00 UTC
Labels: bug, ment1
