### ISSUE TITLE
WCA Results Export Sql Error

### ISSUE THREAD

**Issue by 2016WUJI01** [thewca/worldcubeassociation.org#8901] opened 2024-02-09 08:35 UTC
After I download WCA Results Export data, and import to my mysql.
It shows "ERROR 1062 (23000) at line 56: Duplicate entry '0' for key 'Competitions.PRIMARY'".
And I read the sql file, It shows near all of competitions with '0' in their PRIMARY ID.

**Comment by AlphaSheep** [comment] 2024-02-10 15:27
Hi Software Team. I'm getting the same error. I think it's caused by this bug:
https://jira.mariadb.org/browse/MDEV-31836

Here's a snippet from the export:

```
CREATE TABLE `Persons` (
  `id` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `subid` tinyint NOT NULL DEFAULT '1',
  `name` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `countryId` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `gender` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `Persons`
--

LOCK TABLES `Persons` WRITE;
/*!40000 ALTER TABLE `Persons` DISABLE KEYS */;
INSERT INTO `Persons` VALUES
('Serbia','m','1982BORS01','Jozsef Borsos',1),
('Germany','m','1982BRIN01','Roland Brinkmann',1),
('United Kingdom','m','1982CHIL01','Julian Chilvers',1),
('USA','f','1982FRID01','Jessica Fridrich',1),
('Czech Republic','f','1982FRID01','Jessica Fridrich',2),
('Portugal','m','1982GALR01','Manuel Galrinho',1),
('France','m','1982JEAN01','Jerome Jean-Charles',1),
```

You can see it's creating a table with one column order, then inserting with a different order (alphabetical).

It looks to me like the export was created with MariaDB 10.11.4 and the bug is fixed in versions 10.11.5, 11.0.3, 11.1.2. So an update of the database will hopefully fix this.

**Comment by FinnIckler** [comment] 2024-02-10 15:31
There's already PR to fix this ready to be merged
https://github.com/thewca/worldcubeassociation.org/pull/8903

**Comment by gregorbg** [comment] 2024-02-10 21:09
This should be fixed in the latest export now.
Please re-download the Results Export and confirm :)

**Comment by 2016WUJI01** [comment] 2024-02-11 00:46
Yep, it fixed, but two more table `ar_internal_metadata` and `schema_migrations`.
Might it created by rails ?

**Comment by dunkOnIT** [comment] 2024-03-03 09:38
Not sure about `ar_internal_metadata`, `schema_migration` is definitely created by Rails.

Closing as the issue is resolved.

**Closed by dunkOnIT** 2024-03-03 09:38 UTC
