### ISSUE TITLE
Touch Icon

### ISSUE THREAD

**Issue by lgarron** [thewca/worldcubeassociation.org#918] opened 2016-09-28 09:53 UTC
We should have a touch icon for nice homescreen icons on iOS/Android when people "add to homescreen".

Should be as simple as having a touch-icon image (a single 128x128 image should be fine) and updating every header to include it:

    <link rel="apple-touch-icon" href="touch-icon.png"/>

**Comment by jonatanklosko** [comment] 2016-10-04 20:03
Duplicate of #109.

**Closed by jonatanklosko** 2016-10-04 20:03 UTC
Labels: not-a-priority-will-accept-acceptable-pr

**Comment by lgarron** [comment] 2016-10-04 21:06
> Duplicate of #109.

Heh. :-P
