### ISSUE TITLE
If 5 people are tied at WR99, show them on the rankings page

### ISSUE THREAD

**Issue by LeviGibson** [thewca/worldcubeassociation.org#8375] opened 2023-10-01 23:50 UTC
**Is your feature request related to a problem? Please describe.**
My boy Will Russo has a 22 single in FMC, which places him 98th in the world. However, since a whole lot of people have 22 singles, only the first few show up on the rankings page. 

**Describe the solution you'd like**
Add the rest of the people who have 22 singles to the rankings page because they're still top 100.

**Comment by dunkOnIT** [comment] 2023-10-02 03:54
Closing as duplicate of #4479 - PR's welcome if anyone wants to give the homie Will Russo the recognition they deserve!

**Closed by dunkOnIT** 2023-10-02 03:54 UTC
