### ISSUE TITLE
Zooming on /competitions/ makes comp venue details hard to read.

### ISSUE THREAD

**Issue by aoaaceai** [thewca/worldcubeassociation.org#5461] opened 2020-05-21 03:21 UTC
**Bug Description**
in [the competition list](https://worldcubeassociation.org/competitions), zooming the page can cause longer venue location to overflow.

**To Reproduce**
1. go to [the list](https://worldcubeassociation.org/competitions)
2. Zoom in to about 160%

**Expected behavior**
as the image shown below, the text "Christian College" overflows and ended up under the comp name.

**Screenshots**
![pic](https://user-images.githubusercontent.com/54458354/82519422-395a5180-9b54-11ea-812c-77cf35228218.png)

**Desktop (please complete the following information):**
Windows 10, Firefox 76.0.1

**Smartphone (please complete the following information):**
That's not an issue on the mobile version.

Just curious, maybe make it a table can solve the problem?

**Comment by gregorbg** [comment] 2021-06-20 14:15
Closing as duplicate of #3246

**Closed by gregorbg** 2021-06-20 14:15 UTC
Labels: bug, design, good first issue, low-priority
