### ISSUE TITLE
Error when attempting to close full registration early (here: as Junior Delegate)

### ISSUE THREAD

**Issue by AnnikaStein** [thewca/worldcubeassociation.org#8916] opened 2024-02-15 08:56 UTC
**Describe the bug**
Yesterday we wanted to close registration for Kölner Kubing 2024 early due to very high demand. As confirmed by some co-delegates, this used to work by clicking the Close registration button on the competition edit page and confirming with Yes. When I tried it, the site crashed with an error message stating that registration is already closed. Together with Gregor, Finn we tracked down that this comes from a recently added check introduced in https://github.com/thewca/worldcubeassociation.org/pull/8590 where we are unsure whether it is intentional or not: shall people who have edit permissions but not competition admin permissions be allowed to close registration early or not? If yes, then this is a bug with the logic related to editing_user.can_admin_competitions. If no, we were not aware that this got changed or just properly enforced as a side effect of the mentioned PR and would like a more descriptive error message instead of generic registration is already closed, because the permissions would be the root cause and not the registration being already closed. For example, Gregor could close registration (thanks!) without problems, I think that's because of more permissions, so `editing_user.can_admin_competitions` is True for him.

**To Reproduce**
1. Login to an account where you have competition edit, but not admin permissions.
2. Pick a competition that is already full but registration still open.
3. Try closing registration —> see error.

**Expected behavior**
We would like to understand if this is intentional or not, and if yes, a better error message. If not intentional, remove the admin check and let delegates / orga close registration themselves if they think it’s necessary to do so.

**Screenshots**
![Bildschirmfoto 2024-02-14 um 20 21 28](https://github.com/thewca/worldcubeassociation.org/assets/53974095/1837a258-1471-45b3-923b-857a920ae2f9)
![Bildschirmfoto 2024-02-14 um 20 21 06](https://github.com/thewca/worldcubeassociation.org/assets/53974095/58da1448-8d79-40ef-8ddc-742b218fc611)

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)
 - Browser: Chrome
 - Version: 121.0.6167.139 (Offizieller Build) (arm64)

**Comment by FinnIckler** [comment] 2024-02-15 08:59
@DanielEgdal has the author of the original PR, can you tell us if this change was intentional?

**Comment by DanielEgdal** [comment] 2024-02-15 11:02
I'll paste some quotes from the thread I had with WST:
Gregor: "Note on why this didn't break before: Our test cases for "describe 'POST #orga_close_reg_when_full_limit'" in "competitions_controller_spec" accidentally don't create confirmed competitions. So your check never runs, and we should change the test case to create confirmed competitions. In production, this did not break because the old competition form did not set editing_user_id when pushing the button. So the first "if" in your validation already fails. The new UI always has editing_user_id set, so the check runs and prevents users from clicking the button."

Me: "WCAT wants to prevent competitions from being submitted when the registration deadline has already closed. Skimming the code in place, seems some of the `should_validate_registration_closing?` might be possible to do otherwise. As I cannot test anything, it is hard to say what should be done. 
But, we should not even be calling this check when the competition is confirmed/visible. The website should only complain if the Delegate/organiser wants to set registration to be in the past, before/while submitting to WCAT. It's a while since I implemented this, so I cannot recall if the current way it is written was the only way I could get this to follow the workflow."

Lmk if there are more specific questions.

**Comment by FinnIckler** [comment] 2024-02-15 11:13
if this check should only check if the competition date is set in the past, why are you calling `!editing_user.can_admin_competitions?` ?

**Comment by DanielEgdal** [comment] 2024-02-15 11:33
The idea was that WCAT should be able to bypass potential errors I believe. The logic seems really off in the code, but since the website acted differently beforehand, there was no issues when I was testing the code.

**Comment by dunkOnIT** [comment] 2024-03-12 04:24
@DanielEgdal I believe this is now resolved by #9032 - could you confirm?

**Comment by DanielEgdal** [comment] 2024-03-12 09:11
> @DanielEgdal I believe this is now resolved by #9032 - could you confirm?

I haven't heard any issues since. But Gregor did highlight in the email thread some weeks back that the test cases had to be updated (which I highlighted in my first response), to check the functionality is as intended. I do not see those in the PR you linked. But regardless that might be better to track on a new issue since that is kind of a new topic.

**Closed** 2024-03-21 08:37 UTC
