### ISSUE TITLE
Bug - Old Competition's Registration Requirements

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3257] opened 2018-08-24 01:13 UTC
Right now, competitions previously announced do not include "No on the spot registrations will be accepted". I assume this is because this information is not easily obtainable without hand processing the registration requirements for this information.

However, whenever a competition is updated (say by adding a delegate) this field now appears. Even though the organizer's may have "on-site registrations are allowed" in their requirements. 

I'm not sure if there is a good software solution, but I'll send an email to let everyone know of this issue when updating information on a competition.

**Comment by AlbertoPdRF** [comment] 2018-08-24 07:06
If I understand the issue correctly, the problem is that when a past competition is updated, the default value of `on_the_spot_registration` (`NULL`) gets updated to `false`, right? If that's the case, is there any way to prevent that update for competitions `created_at` before 8/22?

**Comment by Jambrose777** [comment] 2018-08-24 13:04
Another solution is to go through the ~200 announced competitions and clean up the registration requirements. This would involve removing the duplicate registration information and setting the fields appropriately.

I could probably take care of most of these this weekend. And it cleans up the competitions. Thoughts?

**Comment by Goosly** [comment] 2018-08-24 13:16
That would probably be the fastest solution, Jacob. The duplicate information looks very weird on a lot of competitions now :-)

**Comment by Jambrose777** [comment] 2018-08-24 13:18
Might take a long time compared to Alberto’s proposal. But it will make the competitions look better

**Comment by Goosly** [comment] 2018-08-24 13:28
Still, Alberto's proposal would only fix the **error** where "No on the spot registrations will be accepted" is now incorrectly shown.

Your idea is more thorough and will clean up **all duplicate information**. But it is a lot of work indeed.

**Comment by cubewhiz** [comment] 2018-08-26 04:01
Jacob and I started this task. It looks like we will be taking care of this (and duplicate information) manually for all announced future competitions, so we can close this issue.

**Comment by jfly** [comment] 2018-08-26 21:48
Let's keep this open so we can track this task. @Jambrose777 and @cubewhiz, thanks for taking this on, and please feel free to close this when you're done!

**Comment by AlbertoPdRF** [comment] 2018-08-30 11:07
This has been fully taken care of by @Jambrose777 and @cubewhiz, so I'm closing the issue again :P

**Closed by AlbertoPdRF** 2018-08-30 11:07 UTC
