### ISSUE TITLE
Dues calculation no longer takes into account the minimum due amount

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#7143] opened 2022-08-15 16:40 UTC
**Describe the bug**
The dues estimation on WCA when creating a competition no longer takes into account the minimum due amount (for US it is currently $1). This causes the estimation to be wrong: 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/11577241/184677603-e6de55d4-1b26-4487-b3ba-8c67cacdfcf0.png">

**Comment by gregorbg** [comment] 2022-08-17 09:58
For context: When you say "no longer", can you confirm that it was correct at some point in the past? Just wondering because we haven't really touched that part of the code in a while.

**Comment by Jambrose777** [comment] 2022-08-17 15:01
I am 90% certain it was correct when it was implemented, but not certain.

**Comment by notrichardpeng** [comment] 2022-08-26 19:52
Hi Jacob, I'm trying to replicate this locally but on my end it took the minimum amount into account:

![image](https://user-images.githubusercontent.com/58278719/186979920-5b42a8e0-c608-4948-8fbe-b2a380ec4481.png)

I imagine the comp is GA Cubers Turkey Gobblers 2022? Sorry if this was creepy but I logged into your dummy account on dev to see where exactly the issue is :P. But here it appeared fine.

**Comment by Jambrose777** [comment] 2022-08-26 19:56
Just looked at it. It is correct in production now.

I did repro this by doing the following:
Competitions > New competition
Fill in country as United States
Fill in competitor limit (100)
Fill in base registration fee ($5)
Notice it does not account for the minimum.

If I had to guess its not taking into account the country when first creating the forum.

**Comment by notrichardpeng** [comment] 2022-08-26 20:13
I see now. Yeah after hitting "create competition" it becomes correct. I think adding a callback for when country changes can fix this.

**Comment by notrichardpeng** [comment] 2022-08-26 20:24
Actually it wouldn't be that easy; getting the country band needs the backend function `CountryBand.where`, so I don't think it can update dynamically with frontend changes. Maybe the fix here is to just add a note saying something along the lines of "hit Update Competition after changing the country" or "Refresh the page after indicating the country to make estimation accurate"?

**Comment by gregorbg** [comment] 2022-08-31 01:48
I think this should be possible without saving. Note that fields like the "Country" dropdown or the "Currency code" selector can all be dynamically read and evaluated through jQuery.

Right now, you rely on the `@competition` object from Ruby to obtain this information. Of course, you have to save before this value updates. Butt what if you use JS to do something like `var country = $('select[name="competition[country]"]').val()` (and analogously, `var currencyCode = $('select[name="competition[currency_code]"]').val();`)?

Of course, you cannot take those JS variables and stuff them back into the Ruby `CountryBand::BANDS` hash at runtime. What you _can_ do however, is to dynamically gather all of the various values (currency code, country, competitor limit, etc.) using jQuery, then AJAX them down to the Ruby backend, have the backend do all of the complex computation logic that you're (partially) doing in JS right now, and only handle the actual display logic back in the JS world.

This would also make the code a whole lot cleaner in terms of "separation of concerns". What do you think?

**Comment by notrichardpeng** [comment] 2022-08-31 20:14
This sounds like a great solution and I don't have oppositions to it. I'll just need some time to implement it.

**Comment by dunkOnIT** [comment] 2022-10-20 14:13
One question regarding this is whether a React implementation would change some of the elements described here. For example, we are looking to phase out JQUery. Unless this is a high priority item, perhaps the note to "Refresh the page after indicating the country" is our best interim solution?

**Comment by notrichardpeng** [comment] 2022-11-09 04:27
It's been a while, so same question as @dunkOnIT. I think I should still proceed with the jQuery approach? It seems that a React implementation of this page would take considerable effort so I imagine the jQuery/AJAX code could last quite a while.

**Comment by gregorbg** [comment] 2022-11-09 09:44
There is absolutely no need to move the entire competition form to React just for the sake of resolving this issue. You can stick with the jQuery implementation but clean it up a little. Think of it as groundwork and preparation for the full React migration :)

As to the specific implementation, I would like all of the calculations be handled by the backend. JavaScript should not make any kind of assumptions or if-else-cases on how or when or why or which fee to calculate. The only job of JS should be to bundle all the necessary information so that Ruby can make a well-informed decision, AJAX that information down to an endpoint, let the endpoint handle all of the business logic, and then (more or less) stupidly dsiplay whatever the endpoint returns, without thinking about how or why that result came to be.

**Comment by gregorbg** [comment] 2022-12-18 04:30
Fixed per https://github.com/thewca/worldcubeassociation.org/pull/7377

**Closed by gregorbg** 2022-12-18 04:30 UTC
Labels: STATUS: in-progress, TECH: ruby, SERVICE: competition
