### ISSUE TITLE
Access to Roles edit panel is not restricted for Delegates

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#8492] opened 2023-11-05 17:54 UTC
@danieljames-dj just noting that currently any Delegate can access the "Edit Role" panel, select a new role, and hit "Update role" - this then fails due to an error (which is good :D), but it seems like we should disable being able to open the Roles Edit panel for users with insufficient permissions.

![image](https://github.com/thewca/worldcubeassociation.org/assets/52967253/5e7c1a1f-4eff-4276-9201-4069bf9e092a)

**Comment by danieljames-dj** [comment] 2023-11-05 21:00
Hi @dunkOnIT thanks for raising the issue. I'll raise a PR to fix this issue soon. Also this was informed to me by another staff recently and we confirmed that change is not possible because of our backend validations.

**Comment by danieljames-dj** [comment] 2023-12-30 00:02
This is fixed now.

**Closed by danieljames-dj** 2023-12-30 00:02 UTC
Labels: TYPE: bug, TECH: ruby, SERVICE: Users/Entities
