### ISSUE TITLE
[New Section] Organize competition

### ISSUE THREAD

**Issue by StachuDotNet** [thewca/worldcubeassociation.org#12] opened 2015-04-27 21:19 UTC
Right now if someone wants to organize a competition, they have to go 'find their delegate,' resulting in email chains and random 10 year olds with no clue begging for competitions with no idea how to run one.

Wouldn't it be great if there were a page on wca.org that allowed you to 'request a competition consult'?
Such a page would require you to input:
- dates applicable
- requested events
- competition name
- contact details
- where you've already found a location (less back and forth for delegates)
- etc.

Upon submissions, delegates could choose to respond to the requests through a tiny workflow, depending on their personal schedule.

Thoughts?

**Comment by lgarron** [comment] 2015-04-27 23:05
I feel like this is the #1 source of spurious posts to the WAC website form and the WCA forum. We should definitely have this section.

I think there's a wca-website bug about this. @jfly, could you cross-reference?

**Comment by jbcm627** [comment] 2015-04-27 23:27
On the other hand, I don't really want to invite additional requests for competitions in backyards.

While there may be a very rare exception, it is unlikely I would delegate a competition for someone with little or no experience working at competitions. If an organizer does fall in this category, I am (or another delegate is) probably aware of them, and I would prefer to hear from them directly rather than seeing a generic form. Otherwise, my response will always be something along the lines of "go help out at a competition first".

My preference is to instead refer people to something like [wca-website/#9](https://github.com/cubing/wca-website/issues/9), rather than needing to reply individually to many requests.

**Comment by jfly** [comment] 2015-04-28 05:33
@lgarron, are you referring to this comment: https://github.com/cubing/wca-website/issues/15#issuecomment-78199959?

**Comment by jfly** [comment] 2015-08-03 19:22
Possibly related: Chris Olson and kit clement made a video for first time competitors that may be a good think to link to on the wca website.

**Comment by denthebro** [comment] 2021-05-31 03:25
Should this not be closed by now?

**Comment by Jambrose777** [comment] 2021-05-31 06:00
> Should this not be closed by now?

The original post for the issue is talking about a form for requesting a competition without having to go through the head-ache of contacting a Delegate.

I personally don't see a need for this type of form to be implemented as if I were to receive one of these request I would just send them my own version of the info I need to Delegate for someone, but others may have a different opinion. Ron marked this as to close soon, but it might be worth having a bigger discussion before doing so as it still could be a sought after feature.

**Comment by denthebro** [comment] 2021-05-31 07:09
What if the WQAC made such a form and later published it somewhere on the website? I believe that would work better. We can then close this issue and I would later make a PR in the wca-documents repo.

**Comment by dunkOnIT** [comment] 2023-08-31 12:12
Closing - not seeing sufficient demand for this feature. Especially with the contact form and forums, not to mention the growth of Regional Organizations, prospective competitors have other ways of contacting delegates.

**Closed by dunkOnIT** 2023-08-31 12:12 UTC
Labels: AREA: documentation, META: community-feedback
