### ISSUE TITLE
Tooltips cover each other at My Competitions

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1447] opened 2017-03-15 12:34 UTC
This only happens for delegates, I think, since it involves the delegate report.
![image](https://cloud.githubusercontent.com/assets/1881933/23948602/8637fb2e-0962-11e7-9f64-02e532cf6b51.png)

**Comment by jfly** [comment] 2017-03-16 00:51
This is a duplicate of #1170 =)

**Closed by jfly** 2017-03-16 00:51 UTC
