### ISSUE TITLE
WCA Website should show organizers when they misspell everything

### ISSUE THREAD

**Issue by LeviGibson** [thewca/worldcubeassociation.org#7306] opened 2022-10-21 13:59 UTC
**Is your feature request related to a problem? Please describe.**
I'm always embarrassed when I'm working on a competition website and I misspell everything, and the website doesn't have the little red squiggles under the misspelled words. Just in the previous sentience alone I misspelled "embarrassed" and "doesn't" and GitHub kindly pointed it out to me with the little red squiggles.

**Describe the solution you'd like**
Put some squiggles under misspelled words.

**Describe alternatives you've considered**
If an organizer makes a misspelling that goes live on the website, they get banned from the WCA. This would also be effective at reducing misspellings.

**Additional context**
Don't judge me.
![tim](https://user-images.githubusercontent.com/72767501/197213051-6ac945f0-e4f9-4666-b8b1-f3dba7fd8643.png)

**Comment by kr-matthews** [comment] 2022-10-21 16:57
This looks like it's already covered in #7043.

**Comment by dunkOnIT** [comment] 2022-10-25 05:35
Sorry for the frustration caused by this Levi! It appears to be related to how we're tagging our markdown input fields, but beyond that we haven't yet been able to investigate it unfortunately. 

As Kevin says, this issue has been reported, so I'm going to close this issue to avoid duplication. 

**Closed in favour of #7043.**

**Closed by dunkOnIT** 2022-10-25 05:35 UTC

**Comment by dunkOnIT** [comment] 2022-10-25 05:40
Duplicate of #7043
