### ISSUE TITLE
Add proper support for disqualified competitions

### ISSUE THREAD

**Issue by SAuroux** [thewca/worldcubeassociation.org#5335] opened 2020-04-09 09:38 UTC
**Is your feature request related to a problem? Please describe.**
Disqualified competitions (e.g. [PerryOpen2013]( https://www.worldcubeassociation.org/competitions/PerryOpen2013), [CaviteOpen22018](https://www.worldcubeassociation.org/competitions/CaviteOpen22018)) are not currently not well supported, showing the same "Note: This competition is over, we are working to upload the results as soon as possible!" message as for recently finished competitions.

**Describe the solution you'd like**
This message should not appear for disqualified competitions where results will of course not be uploaded as soon as possible. Maybe an additional column for the Competitions table will be the cleanest solution.

**Describe alternatives you've considered**
I have already had a look into the [competition model](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition.rb#L394). Unfortunately, forcing results_posted? to be True by setting results_posted_at and results_posted_by yields a website error, probably because it triggers some other code assuming the results exist.

**Comment by LinusFresz** [comment] 2020-04-09 14:30
Duplicate of https://github.com/thewca/worldcubeassociation.org/issues/3970?

**Comment by danieljames-dj** [comment] 2020-04-12 20:17
I wanted to comment something regarding this, but since there is already a discussion initiated in the duplicate that @LinusFresz mentioned, I'll comment there.

**Closed** 2020-05-17 08:12 UTC
