### ISSUE TITLE
WCA ID claim related columns weirdness

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#889] opened 2016-09-13 20:04 UTC
Some console results that are worth investigating
```
irb(main):007:0> User.where(delegate_id_to_handle_wca_id_claim: nil).where.not(unconfirmed_wca_id: nil).count
   (90.9ms)  SELECT COUNT(*) FROM `users` WHERE `users`.`delegate_id_to_handle_wca_id_claim` IS NULL AND (`users`.`unconfirmed_wca_id` IS NOT NULL)
=> 2596
irb(main):008:0> 
```
```
irb(main):009:0> User.where(delegate_id_to_handle_wca_id_claim: nil).where.not(unconfirmed_wca_id: nil, wca_id: nil).count
   (99.1ms)  SELECT COUNT(*) FROM `users` WHERE `users`.`delegate_id_to_handle_wca_id_claim` IS NULL AND (`users`.`unconfirmed_wca_id` IS NOT NULL) AND (`users`.`wca_id` IS NOT NULL)
=> 133
irb(main):010:0>
 ```

**Comment by jonatanklosko** [comment] 2016-09-16 22:46
That's interesting
```
irb(main):004:0> User.where(delegate_id_to_handle_wca_id_claim: nil).where.not(unconfirmed_wca_id: nil).distinct.pluck(:unconfirmed_wca_id)
   (98.0ms)  SELECT DISTINCT `users`.`unconfirmed_wca_id` FROM `users` WHERE `users`.`delegate_id_to_handle_wca_id_claim` IS NULL AND (`users`.`unconfirmed_wca_id` IS NOT NULL)
=> [""]
```
In addition the selected users have been updated recently so it's not an old fixed bug living here. [There](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/spec/controllers/users_controller_spec.rb#L67-L81) are tests which should ensure everything works.

**Comment by jfly** [comment] 2016-09-17 06:20
Oh, so everyone who has a `unconfirmed_wca_id` with a NULL `delegate_id_to_handle_wca_id_claim` actually has empty string as their `unconfirmed_wca_id`?

@jonatanklosko why does the fact that these users have been updated recently mean that this is not an old fixed bug?

[This code](https://github.com/jfly/worldcubeassociation.org/blob/d8d9e728e8a570b21ec1836a670e79d832634387/WcaOnRails/app/models/user.rb#L100-L107) is incredibly difficult to follow, so it's hard for me to imagine how this could happen via code inspection. It will be interesting to revisit this issue and see if the number of problematic users changes.

**Comment by jonatanklosko** [comment] 2016-09-17 19:51
It's either `nil` or an empty string
```
irb(main):011:0> User.where(delegate_id_to_handle_wca_id_claim: nil).distinct.pluck(:unconfirmed_wca_id)
   (140.6ms)  SELECT DISTINCT `users`.`unconfirmed_wca_id` FROM `users` WHERE `users`.`delegate_id_to_handle_wca_id_claim` IS NULL
=> [nil, ""]
```

@jfly Hmm actually I'm not sure, what I thought is that assuming that all of the users didn't update their profiles then we could treat `updated_at` as the claim confirmation date and thus see that probably some `unconfirmed_wca_id`s have been reseted to `""` recently. It doesn't seem like some good info though, so ignore this.

I tried the claim-confirmation process locally and the `unconfirmed_wca_id` was correctly reseted to `nil`.

**Comment by jfly** [comment] 2016-09-23 20:15
I just checked, and there *are* more occurrences of this since I last checked, which proves this is not just a problem we had at one point in the past.

We're up to 137 problematic users, whereas it was only 133 when @jonatanklosko created this issue: https://github.com/cubing/worldcubeassociation.org/issues/889#issue-176736042
```
> SELECT COUNT(*) FROM `users` WHERE `users`.`delegate_id_to_handle_wca_id_claim` IS NULL AND (`users`.`unconfirmed_wca_id` IS NOT NULL) AND (`users`.`wca_id` IS NOT NULL)
137
```

I was able to find an occurence of us setting `unconfirmed_wca_id` to empty string here:

```
~/worldcubeassociation.org/WcaOnRails @production> zgrep -C 100 "UPDATE..users..SET.*unconfirmed_wca_id" log/production.log.4.gz
...
I, [2016-09-20T00:00:59.105449 #12277]  INFO -- : Started PATCH "/users/30047" for 131.252.200.231 at 2016-09-20 00:00:59 +0000
D, [2016-09-20T00:00:59.107194 #12277] DEBUG -- :   ^[[1m^[[36mUser Load (0.3ms)^[[0m  ^[[1mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 259  ORDER BY `users`.`id` ASC LIMIT 1^[[0m
I, [2016-09-20T00:00:59.108536 #12277]  INFO -- : Processing by UsersController#update as HTML
I, [2016-09-20T00:00:59.108602 #12277]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "section"=>"general", "user"=>{"name"=>"Grigoriy Shmigol", "dob"=>"[FILTERED]", "gender"=>"m", "country_iso2"=>"US", "unconfirmed_wca_id"=>"", "wca_id"=>"2016SHMI01"}, "commit"=>"Save", "id"=>"30047"}
D, [2016-09-20T00:00:59.109504 #12277] DEBUG -- :   ^[[1m^[[35mUser Load (0.2ms)^[[0m  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 30047 LIMIT 1
D, [2016-09-20T00:00:59.110729 #12277] DEBUG -- :   ^[[1m^[[36mTeam Load (0.2ms)^[[0m  ^[[1mSELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1^[[0m
D, [2016-09-20T00:00:59.111807 #12277] DEBUG -- :   ^[[1m^[[35m (0.3ms)^[[0m  SELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 259 AND (end_date IS NULL OR end_date > '2016-09-20') AND `team_members`.`team_id` = 2
D, [2016-09-20T00:00:59.112324 #12277] DEBUG -- :   ^[[1m^[[36mTeam Load (0.2ms)^[[0m  ^[[1mSELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'results' LIMIT 1^[[0m
D, [2016-09-20T00:00:59.113221 #12277] DEBUG -- :   ^[[1m^[[35m (0.2ms)^[[0m  SELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 259 AND (end_date IS NULL OR end_date > '2016-09-20') AND `team_members`.`team_id` = 1
D, [2016-09-20T00:00:59.113678 #12277] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 30047 LIMIT 1^[[0m  [["id", "30047"]]
D, [2016-09-20T00:00:59.114003 #12277] DEBUG -- :   ^[[1m^[[35mCACHE (0.0ms)^[[0m  SELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1  [["friendly_id", "software"]]
D, [2016-09-20T00:00:59.114621 #12277] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 259 AND (end_date IS NULL OR end_date > '2016-09-20') AND `team_members`.`team_id` = 2^[[0m  [["user_id", 259], ["team_id", 2]]
D, [2016-09-20T00:00:59.114853 #12277] DEBUG -- :   ^[[1m^[[35mCACHE (0.0ms)^[[0m  SELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1  [["friendly_id", "software"]]
D, [2016-09-20T00:00:59.115425 #12277] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 259 AND (end_date IS NULL OR end_date > '2016-09-20') AND `team_members`.`team_id` = 2^[[0m  [["user_id", 259], ["team_id", 2]]
D, [2016-09-20T00:00:59.115715 #12277] DEBUG -- :   ^[[1m^[[35mCACHE (0.0ms)^[[0m  SELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1  [["friendly_id", "software"]]
D, [2016-09-20T00:00:59.116318 #12277] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 259 AND (end_date IS NULL OR end_date > '2016-09-20') AND `team_members`.`team_id` = 2^[[0m  [["user_id", 259], ["team_id", 2]]
D, [2016-09-20T00:00:59.129526 #12277] DEBUG -- :   ^[[1m^[[35m (0.1ms)^[[0m  BEGIN
D, [2016-09-20T00:00:59.131393 #12277] DEBUG -- :   ^[[1m^[[36mPerson Load (0.3ms)^[[0m  ^[[1mSELECT  `rails_persons`.* FROM `rails_persons` WHERE `rails_persons`.`wca_id` = '2016SHMI01' AND `rails_persons`.`subId` = 1 LIMIT 1^[[0m
D, [2016-09-20T00:00:59.132080 #12277] DEBUG -- :   ^[[1m^[[35mCountry Load (0.2ms)^[[0m  SELECT  `Countries`.* FROM `Countries` WHERE `Countries`.`id` = 'USA' LIMIT 1
D, [2016-09-20T00:00:59.134310 #12277] DEBUG -- :   ^[[1m^[[36mSQL (0.3ms)^[[0m  ^[[1mUPDATE `users` SET `unconfirmed_wca_id` = '', `updated_at` = '2016-09-20 00:00:59' WHERE `users`.`id` = 30047^[[0m
D, [2016-09-20T00:00:59.138935 #12277] DEBUG -- :   ^[[1m^[[35m (3.9ms)^[[0m  COMMIT
I, [2016-09-20T00:00:59.139743 #12277]  INFO -- : Redirected to https://www.worldcubeassociation.org/users/30047/edit?section=general
I, [2016-09-20T00:00:59.139876 #12277]  INFO -- : Completed 302 Found in 31ms (ActiveRecord: 5.9ms)
I, [2016-09-20T00:00:59.140232 #12277]  INFO -- : [User Id] Request was made by user id: 259
```

And here's an example of someone approving a WCA ID, and the `unconfirmed_wca_id` correctly being set to NULL:

I, [2016-09-19T10:34:36.243389 #2254]  INFO -- : Started PATCH "/users/30005" for 89.116.85.193 at 2016-09-19 10:34:36 +0000
D, [2016-09-19T10:34:36.245105 #2254] DEBUG -- :   ^[[1m^[[35mUser Load (0.3ms)^[[0m  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1484  ORDER BY `users`.`id` ASC LIMIT 1
I, [2016-09-19T10:34:36.246418 #2254]  INFO -- : Processing by UsersController#update as HTML
I, [2016-09-19T10:34:36.246482 #2254]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "section"=>"general", "user"=>{"name"=>"Irma Jankauskaitė", "dob"=>"[FILTERED]", "gender"=>"f", "country_iso2"=>"LT", "unconfirmed_wca_id"=>"", "wca_id"=>"2016JANK02"}, "commit"=>"Save", "id"=>"30005"}
D, [2016-09-19T10:34:36.247369 #2254] DEBUG -- :   ^[[1m^[[36mUser Load (0.2ms)^[[0m  ^[[1mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 30005 LIMIT 1^[[0m
D, [2016-09-19T10:34:36.248581 #2254] DEBUG -- :   ^[[1m^[[35mTeam Load (0.2ms)^[[0m  SELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1
D, [2016-09-19T10:34:36.249634 #2254] DEBUG -- :   ^[[1m^[[36m (0.3ms)^[[0m  ^[[1mSELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 1484 AND (end_date IS NULL OR end_date > '2016-09-19') AND `team_members`.`team_id` = 2^[[0m
D, [2016-09-19T10:34:36.250193 #2254] DEBUG -- :   ^[[1m^[[35mTeam Load (0.2ms)^[[0m  SELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'results' LIMIT 1
D, [2016-09-19T10:34:36.251089 #2254] DEBUG -- :   ^[[1m^[[36m (0.2ms)^[[0m  ^[[1mSELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 1484 AND (end_date IS NULL OR end_date > '2016-09-19') AND `team_members`.`team_id` = 1^[[0m
D, [2016-09-19T10:34:36.251518 #2254] DEBUG -- :   ^[[1m^[[35mCACHE (0.0ms)^[[0m  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 30005 LIMIT 1  [["id", "30005"]]
D, [2016-09-19T10:34:36.251860 #2254] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1^[[0m  [["friendly_id", "software"]]
D, [2016-09-19T10:34:36.252486 #2254] DEBUG -- :   ^[[1m^[[35mCACHE (0.0ms)^[[0m  SELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 1484 AND (end_date IS NULL OR end_date > '2016-09-19') AND `team_members`.`team_id` = 2  [["user_id", 1484], ["team_id", 2]]
D, [2016-09-19T10:34:36.252713 #2254] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1^[[0m  [["friendly_id", "software"]]
D, [2016-09-19T10:34:36.253308 #2254] DEBUG -- :   ^[[1m^[[35mCACHE (0.0ms)^[[0m  SELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 1484 AND (end_date IS NULL OR end_date > '2016-09-19') AND `team_members`.`team_id` = 2  [["user_id", 1484], ["team_id", 2]]
D, [2016-09-19T10:34:36.253597 #2254] DEBUG -- :   ^[[1m^[[36mCACHE (0.0ms)^[[0m  ^[[1mSELECT  `teams`.* FROM `teams` WHERE `teams`.`friendly_id` = 'software' LIMIT 1^[[0m  [["friendly_id", "software"]]
D, [2016-09-19T10:34:36.254178 #2254] DEBUG -- :   ^[[1m^[[35mCACHE (0.0ms)^[[0m  SELECT COUNT(*) FROM `team_members` WHERE `team_members`.`user_id` = 1484 AND (end_date IS NULL OR end_date > '2016-09-19') AND `team_members`.`team_id` = 2  [["user_id", 1484], ["team_id", 2]]
D, [2016-09-19T10:34:36.263314 #2254] DEBUG -- :   ^[[1m^[[36m (0.1ms)^[[0m  ^[[1mBEGIN^[[0m
D, [2016-09-19T10:34:36.265497 #2254] DEBUG -- :   ^[[1m^[[35mPerson Load (0.3ms)^[[0m  SELECT  `rails_persons`.* FROM `rails_persons` WHERE `rails_persons`.`wca_id` = '2016JANK02' AND `rails_persons`.`subId` = 1 LIMIT 1
D, [2016-09-19T10:34:36.266211 #2254] DEBUG -- :   ^[[1m^[[36mCountry Load (0.2ms)^[[0m  ^[[1mSELECT  `Countries`.* FROM `Countries` WHERE `Countries`.`id` = 'Lithuania' LIMIT 1^[[0m
D, [2016-09-19T10:34:36.267663 #2254] DEBUG -- :   ^[[1m^[[35mUser Load (0.3ms)^[[0m  SELECT  `users`.* FROM `users` WHERE `users`.`wca_id` = '2016JANK02' LIMIT 1
D, [2016-09-19T10:34:36.268863 #2254] DEBUG -- :   ^[[1m^[[36mUser Load (0.2ms)^[[0m  ^[[1mSELECT `users`.* FROM `users` WHERE `users`.`wca_id` = '2016JANK02'^[[0m
D, [2016-09-19T10:34:36.270569 #2254] DEBUG -- :   ^[[1m^[[35mSQL (0.5ms)^[[0m  UPDATE `users` SET `wca_id` = '2016JANK02', `unconfirmed_wca_id` = NULL, `delegate_id_to_handle_wca_id_claim` = NULL, `updated_at` = '2016-09-19 10:34:36' WHERE `users`.`id` = 30005
D, [2016-09-19T10:34:36.282677 #2254] DEBUG -- :   ^[[1m^[[36m (3.2ms)^[[0m  ^[[1mCOMMIT^[[0m
I, [2016-09-19T10:34:36.283418 #2254]  INFO -- : Redirected to https://www.worldcubeassociation.org/users/30005/edit?section=general
I, [2016-09-19T10:34:36.283582 #2254]  INFO -- : Completed 302 Found in 37ms (ActiveRecord: 5.9ms)
I, [2016-09-19T10:34:36.283912 #2254]  INFO -- : [User Id] Request was made by user id: 1484

**Comment by jfly** [comment] 2016-09-23 20:20
@jonatanklosko, could the above behavior occur if someone tries to approve the same WCA ID twice?

**Comment by jonatanklosko** [comment] 2016-09-24 21:14
That's really interesting that the first pice of log shows updating *only* `unconfirmed_wca_id` (without `wca_id` and `delegate_id_to_handle_wca_id_claim` involved). So far I dunno when this happens, maybe the second condition fails [here](https://github.com/cubing/worldcubeassociation.org/blob/d8d9e728e8a570b21ec1836a670e79d832634387/WcaOnRails/app/models/user.rb#L101). Will investigate further later.

**Closed** 2016-09-26 19:52 UTC
Labels: bug
