### ISSUE TITLE
WCA ID not displayed when claimed after registration

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1012] opened 2016-11-16 18:46 UTC
Please see [here](https://www.worldcubeassociation.org/competitions/UgineJeuetJouet2016/registrations), the WCA ID of Thomas Duplessis doesn't show up, even though he did claim it a few days ago.
Interestingly, it shows up correctly from the admin registrations view.

FTR here are both check before displaying the id, no idea why `.present?` is false though:
In `edit_registrations.html.erb`
```ruby
                <% if registration.wca_id %>
                  <%= render "shared/wca_id", wca_id: registration.wca_id %>
                <% end %>
```

In `index.html.erb`
```ruby
              <% if registration.wca_id.present? %>
                <%= render "shared/wca_id", wca_id: registration.wca_id %>
              <% end %>
```

Is `.present?` behaving in the expected way?

I'll assign myself this weekend if it's not been done by then.

**Comment by jfly** [comment] 2016-11-16 18:51
We should definitely clear up that inconsistency between using `present?` and not using `present?`, but I suspect the issue is actually related to caching. Note that we cache the index page here: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/registrations/index.html.erb#L4. I fear that when a user is edited, their corresponding registrations don't update, so our cache key doesn't break.

**Comment by larspetrus** [comment] 2016-11-18 06:07
If `.wca_id` is an empty or whitespace string, `wca_id.present?` would be different from  `wca_id`.

The way to invalidate the cache when the user changes is something like this:

`cache ["registrations_index", @competition.events, @registrations.pluck(:id), @registrations.maximum(:updated_at), common.user.updated_at]`

Yeah, cache invalidation is a pain, especially to maintain as you change the page. Because it's very hard to write tests for.

**Comment by jfly** [comment] 2016-11-20 08:18
> The way to invalidate the cache when the user changes is something like this:
> 
> cache ["registrations_index", @competition.events, @registrations.pluck(:id), @registrations.maximum(:updated_at), common.user.updated_at]

What is `common` here? Also, is there a reason you closed this issue? I've reopened it, please reclose it if I'm missing stuff.

**Comment by larspetrus** [comment] 2016-11-20 16:14
`common.user` is how the user is accessed in `WcaOnRails/app/views/registrations/index.html.erb`. I don't know what it is, just reading the code.

I must have hit the wrong button by mistake.

**Comment by viroulep** [comment] 2016-11-21 20:54
I'm not sure how to reproduce it locally...
I quickly tried something simple as removing a WCA ID, registering this person to a comp, then claim/edit back the ID and the registrations view updated immediately.

Is there a chance the aforementioned cache would be disable locally?

**Comment by jfly** [comment] 2016-11-22 02:26
> Is there a chance the aforementioned cache would be disable locally?

I believe so. See https://github.com/thewca/worldcubeassociation.org/blob/07d766cf3132169dde69d3cdbc8f1a2527ed25d5/WcaOnRails/config/environments/production.rb#L60 where it is enabled for production.

**Closed** 2016-11-23 10:08 UTC
Labels: bug
